### PR TITLE
Change base assumptions in order to make clear what we feel about…

### PR DESCRIPTION
**Pull request by sylphiae**
…Lean In feminists

### CODE REVIEW

**Comment by carlyrobison** [comment]
Perhaps squash the two commits before you merge? I like this.

**Comment by anaulin** [comment]
@carlyrobison our default merge setting is "Squash and merge", so it will get squashed regardless.

**Comment by antislice** [comment]
LGTM (also wow github's interface has changed a bunch since I last looked at a PR here)

**Review by anaulin — APPROVED** [review]

**Review by brittag — APPROVED** [review]
We received about a dozen positive responses and one ambivalent/negative response. We want to acknowledge and keep in mind that many other spaces with progressive/anti-capitalist politics often have negative experiences for historically-excluded people. As always, it is important for DU to strive to be a safer space and build processes and culture toward it.

**Pull request merged**
